characters modal
Retropen-Bar/smashtheque-app pull request #49
Opened 2021-06-29 16:33 UTC by levraipixel

2021-06-30 10:34 UTC, Liombe requested changes

2021-06-30 10:34 UTC, Liombe commented on app/javascript/stylesheets/application_v2/molecules/_characters_cards.scss
> +.card.characters-card {
Pour continuer la logique de nommage des classes, on va plutôt mettre card-<modifier_name>. Ce component est réutilisé autrepart, donc je pense pas que mettre tout le style de card-characters soit une bonne idée. Il faudrait ajouter un autre modifier, par exemple card-box, où on met tous les styles commun à une box, puis ensuite on vient ajouter la couche de style spécifique à une card-characters.

2021-06-30 10:34 UTC, Liombe commented on app/javascript/stylesheets/application_v2/molecules/_characters_cards.scss
> +    color: $red;
Il faudrait mettre les autres couleurs aussi et pour les couleurs de sections, utiliser les couleurs du même nom et pas directement la couleur. Genre section "player" => $player et pas $red

2021-06-30 10:34 UTC, Liombe commented on app/javascript/stylesheets/application_v2/molecules/_characters_cards.scss
> +      font-size: 12px;
Plutôt utiliser des rem pour les font-size

2021-06-30 10:34 UTC, Liombe commented on app/javascript/stylesheets/application_v2/molecules/_modals.scss
> +.modal-dialog.modal-auto {
Pour suivre la logique de nommage, mettre plutôt `modal-dialog-auto`

2021-06-30 10:34 UTC, Liombe commented on app/javascript/stylesheets/application_v2/molecules/_cards.scss
> +    }
ça c'est plutôt du style de card-box

2021-06-30 10:38 UTC, Liombe requested changes

2021-06-30 10:38 UTC, Liombe commented on app/javascript/stylesheets/application_v2/molecules/_characters_cards.scss
> +.card.characters-card {
Du coup changer le nom aussi de fichier ex: box et mettre tous ses modifiers dedans

2021-07-02 11:46 UTC, levraipixel commented on app/javascript/stylesheets/application_v2/molecules/_modals.scss
> +.modal-dialog.modal-auto {
ben là c'était pour correspondre aux classes `modal-lg`, `modal-xl` etc de Bootstrap. Tu veux que je change quand même ?

2021-07-02 11:47 UTC, levraipixel commented on app/javascript/stylesheets/application_v2/molecules/_characters_cards.scss
> +      font-size: 12px;
Comment tu fais pour 15px qui vaut 0.938rem, du coup ?

2021-07-03 19:31 UTC, Liombe requested changes
Merci pour le mini showcase :D  Encore 2-3 bricoles à changer et on devrait être bons

![image](https://user-images.githubusercontent.com/16174252/124365050-da677700-dc45-11eb-96c6-df38d968ea24.png)
Il y a une margin en trop

2021-07-03 19:31 UTC, Liombe commented on app/javascript/stylesheets/application_v2/molecules/_modals.scss
> +.modal-dialog.modal-auto {
Ah oui en effet, je pensais que la classe modal-* se mettait sur le parent. On peut laisser comme ça

2021-07-03 19:31 UTC, Liombe commented on app/javascript/stylesheets/application_v2/molecules/_lists.scss
> +        color: $gray-light;
plutôt "currentColor" ici pour que la couleur de l'icône change avec la couleur au hover du lien

2021-07-04 13:54 UTC, merged